name: Publish GTFS

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "17 2 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup tools
        run: bash setup.bash
      - name: Build
        run: bash run.bash
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out